### PR TITLE
Updating Node version in Engines spec in package.json

### PR DESCRIPTION
**Pull request by aakash2602**
Updated Node version from 0.12 to 1.4 in package.json Engines Spec

Fixes Issue #509

### CODE REVIEW

**Comment by ziluvatar** [comment]
I was going to check if the package is still compatible with that old version, however, I think it is better to state in the package json the versions we actually care about (we have CI set on them), so that would be `>=4` for now. Do you want to update it?

**Comment by aakash2602** [comment]
where do you want me to update that in package json?

**Comment by MitMaro** [comment]
I think @ziluvatar was saying to set the node version to `>=4`:

```
"node": ">=4"
```

**Comment by aakash2602** [comment]
Ok will do that now

**Comment by ziluvatar** [comment]
Thanks MitMaro, I was wondering what kind of release this should be, I think it will be in the next patch one, because, in the project we were really treating node 4 as the minimum node version, this is a fix just for the package.json (we could have broken compatibility with older than v4 at any moment, since it would have been fine to us).

**Pull request merged**
