### PR TITLE
fix(stubs): allow decode method to be stubbed

### PR DESCRIPTION
**Pull request by jakelacey2012**
### Description

This PR allows `.decode` to be stubbed.

### References

- https://github.com/auth0/node-jsonwebtoken/issues/870

### Testing

> Describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.
>
> Also include details of the environment this PR was developed in (language/platform/browser version).

- [ ] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [x] All active GitHub checks for tests, formatting, and security are passing
- [x] The correct base branch is being used, if not the default branch

### CODE REVIEW

**Comment by panva** [comment]
@jakelacey2012 just revert 15a1bc449ab529d540eb9c2be4e093f9f5b0278d to solve #875, #870, and  possibly also #876.

**Comment by kento-machida** [comment]
Revert https://github.com/auth0/node-jsonwebtoken/commit/15a1bc449ab529d540eb9c2be4e093f9f5b0278d to solve also https://github.com/auth0/node-jsonwebtoken/issues/866

**Comment by macrouch** [comment]
> Revert [15a1bc4](https://github.com/auth0/node-jsonwebtoken/commit/15a1bc449ab529d540eb9c2be4e093f9f5b0278d) to solve also #866

This fixes my issue with using
```
jest.spyOn(jwt, 'decode').mockImplementation(() => { ... })

**Review by chimingyip — APPROVED** [review]

**Comment by harishsambasivam** [comment]
+1

**Review by panva — APPROVED** [review]

**Comment by sunkarabhargava** [comment]
@chimingyip @CharlesRea @julienwoll @shane-tomlinson @floresmatias0  @mcastany Can you guys, please help us by merging this PR & release a new version ? many of our projects are in trouble due to this.!

**Review by ArturKlajnerok — APPROVED** [review]

**Comment by ksstoneware** [comment]
Glad to see this is merged but we're still blocked until there is a new release. Anyone know how soon that will occur?

**Comment by NickHeap2** [comment]
+1 for waiting for the new release.

**Comment by diegopamio** [comment]
Any clue when this will be released?

**Comment by mohamedjkr** [comment]
👍

**Comment by FoxMessenger** [comment]
Are there any updates to this release?

**Comment by kuhiga** [comment]
@jakelacey2012 Thanks for opening and merging this PR. Are you able to do a release to get this in?

**Comment by jakelacey2012** [comment]
Thank you for patience with this issue, this has been release in https://www.npmjs.com/package/jsonwebtoken/v/9.0.1 - thank you.

**Comment by lorand-horvath** [comment]
> Thank you for patience with this issue, this has been release in https://www.npmjs.com/package/jsonwebtoken/v/9.0.1 - thank you.

Could you tag release 9.0.1 please? The latest tag on https://github.com/auth0/node-jsonwebtoken/tags is still 9.0.0

**Comment by lorand-horvath** [comment]
> Thank you for patience with this issue, this has been release in https://www.npmjs.com/package/jsonwebtoken/v/9.0.1 - thank you.

@jakelacey2012 Could you tag release 9.0.1 please? The latest tag on https://github.com/auth0/node-jsonwebtoken/tags is still 9.0.0 Thanks!

**Comment by jakelacey2012** [comment]
@lorand-horvath no problem you can find the tag here https://github.com/auth0/node-jsonwebtoken/tree/v9.0.1

**Pull request merged**
