### PR TITLE
remove lodash

### LINKED ISSUE #878: Version 9.0.0 Increased bundle size, probably due to lodash import
### Description

When trying to update to 9.0.0 we noticed that the bundle size of jsonwebtoken had increased quite a lot, making a small app of ours exceed a max size limit at a cloud platform.

It seems to us at least that it might be due to importing the whole lodash package in package.json instead of just the functions used, introduced in this commit: ecdf6cc6073ea13a7e71df5fad043550f08d0fa6

I realise this doesn't necessarily fit all that well under "bug", sorry in that case.

### Reproduction
Here's two screenshots from bundlephobia comparing 8.5.1 vs 9.0.0

**8.5.1:**
image
image

**9.0.0:**
image
image

### Environment
- **Version of this library used:** 9.0.0

### PR DESCRIPTION
**Pull request by Uzlopak**
Resolves #878 

By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

> Describe the purpose of this PR along with any background information and the impacts of the proposed change. For the benefit of the community, please do not assume prior context.
>
> Provide details that support your chosen implementation, including: breaking changes, alternatives considered, changes to the API, etc.
>
> If the UI is being changed, please provide screenshots.

### References

> Include any links supporting this change such as a:
>
> - GitHub Issue/PR number addressed or fixed
> - Auth0 Community post
> - StackOverflow post
> - Support forum thread
> - Related pull requests/issues from other repos
>
> If there are no references, simply delete this section.

### Testing

> Describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.
>
> Also include details of the environment this PR was developed in (language/platform/browser version).

- [ ] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used, if not the default branch

### CODE REVIEW

**Comment by KuSh** [comment]
Reverting to per module packages as it was before https://github.com/auth0/node-jsonwebtoken/commit/ecdf6cc6073ea13a7e71df5fad043550f08d0fa6 could do the  same without reimplementing the wheel

**Comment by Uzlopak** [comment]
I think it is pure garbage to use lodash at all. And the only reason I "reinvented" the wheel was because lodash garbage was used in the first place and there could be some maniac using Number-classes and it would be backwards breaking to not use that isNumber functionality. The same with once and isPlainObject. It is only for backwards compatibility.

**Comment by KuSh** [comment]
> I think it is pure garbage to use lodash at all. And the only reason I "reinvented" the wheel was because lodash garbage was used in the first place and there could be some maniac using Number-classes and it would be backwards breaking to not use that isNumber functionality. The same with once and isPlainObject. It is only for backwards compatibility.

I'm not found of lodash neither but it as the avantage of being tested and used by many, contrary to your implementations. As the goal is to reduce final package sise importing individual methods will accomplish the same without maintenance burden nor testing on node-jsonwebtoken side but with the guarantee that those methods are well tested

**Review by araphiel-chwy — APPROVED** [review]

**Review by araphiel-chwy — CHANGES_REQUESTED** [review]
My apologies for the accidental approval.

There might be some hesitancy with this approach - so here's a lower impact alternative.

**Comment by Uzlopak** [comment]
Closing due to inactivity

**Pull request closed without merging**
