### PR TITLE
added async signing

### PR DESCRIPTION
**Pull request by lukewestby**
This PR addresses issue #106. Feedback would be appreciated, especially around whether the unit test is sufficient. Thanks!

### CODE REVIEW

**Comment by syzer** [comment]
:+1:

**Comment by jfromaniello** [comment]
Thank you! pulished as `v5.1.0`

**Comment by syzer** [comment]
awesome!!! :+1:

**Comment by lukewestby** [comment]
No problem! This library is a cornerstone for me, I'm happy to help.

**Comment by Nepoxx** [comment]
FYI: While this is great, it does not respect the error first callback convention. This unfortunately means that for instanct this does not work with Bluebird's `promisify` or `.fromCallback()`.

**Comment by lukewestby** [comment]
@Nepoxx since this function doesn't have a failure case would you suggest just always passing `undefined` to the first arg of the callback?

**Comment by Nepoxx** [comment]
I'd say `null`.

This isn't big issue for me, changing this would break backwards compatibility. I **think** it should be changed to return `null`/`undefined` as to be more standard (`verify`'s callback uses error-first).

Thoughts?

**Pull request merged**
