### PR TITLE
Add payload field to defined errors

### PR DESCRIPTION
**Pull request by mtpc**
In some case we still want to access the parsed payload despite the token being considered invalid for any reason whatsoever.

### CODE REVIEW

**Comment by ziluvatar** [comment]
Can you bring some example? Because you should not trust any information of the payload if it was considered invalid.

**Comment by mtpc** [comment]
For example the token might have expired, but we still want to access its payload for some token renewal logic.
It might indeed not be a good idea to trust the information of an invalid token, but that's ultimately a decision to be taken by the application logic.

**Comment by ziluvatar** [comment]
Can't you simply call `jwt.decode` in case of error? That would solve it without making the lib expose a payload that the lib consider invalid/no-trusted.

**Comment by mtpc** [comment]
Generally speaking, the whole problem is to access the parsed payload in case of error without having to decode the token *once again*. A better solution than exposing it in errors might exist though, you're right.

**Comment by ziluvatar** [comment]
Since the normal execution is not to get an error, I think if someone is interested in some information in that case it wouldn't be a pain to decode it.

**Pull request closed without merging**
