### PR TITLE
issues 905: Update package.json SEMVER 7.5.4

### PR DESCRIPTION
**Pull request by SEKERM**
By submitting a PR to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md). Please see the [contributing guidelines](https://github.com/auth0/.github/blob/master/CONTRIBUTING.md) for how to create and submit a high-quality PR for this repo.

### Description

> Describe the purpose of this PR along with any background information and the impacts of the proposed change. For the benefit of the community, please do not assume prior context.
>
> Provide details that support your chosen implementation, including: breaking changes, alternatives considered, changes to the API, etc.
>
> If the UI is being changed, please provide screenshots.

### References

> Include any links supporting this change such as a:
>
> - GitHub Issue/PR number addressed or fixed
> - Auth0 Community post
> - StackOverflow post
> - Support forum thread
> - Related pull requests/issues from other repos
>
> If there are no references, simply delete this section.

### Testing

> Describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors.
>
> Please include any manual steps for testing end-to-end or functionality not covered by unit/integration tests.
>
> Also include details of the environment this PR was developed in (language/platform/browser version).

- [ ] This change adds test coverage for new/changed/fixed functionality

### Checklist

- [ ] I have added documentation for new/changed functionality in this PR or in auth0.com/docs
- [ ] All active GitHub checks for tests, formatting, and security are passing
- [ ] The correct base branch is being used, if not the default branch

### CODE REVIEW

**Review by moddx — APPROVED** [review]
LGTM

**Comment by moddx** [comment]
Maybe @jakelacey2012 could approve this?

**Review by fang2hou — APPROVED** [review]

**Comment by ashrash** [comment]
Any update on when will this be pushed ?

**Comment by SEKERM** [comment]
@jakelacey2012 can you please take over at this point?

**Comment by RDarnel** [comment]
Are there any updates on getting a final approval for this PR?

**Review by fang2hou — APPROVED** [review]
LGTM.

I have tested all the use cases in node-jsonwebtoken, comparing the results between semver 7.3.8 and semver 7.5.4. There is no differences I found.

**Comment by dragan-novakovic** [comment]
Hi  @moddx any updates on this?

**Comment by visnicka** [comment]
hey guys, thanks for the hard work!
is there a chance we could get update on the estimated time of fix?

**Comment by moddx** [comment]
Hey @dragan-novakovic ,
I'm not part of auth0 and don't have write access to the repository.

Judging by the sheer number of open PRs the repo seems pretty neglected..

Maybe @woloski could delegate this to someone?

**Review by huynhdev24 — APPROVED** [review]

**Comment by SEKERM** [comment]
Merging is blocked
Merging can be performed automatically with **1 approving review.** <<

**Comment by SEKERM** [comment]
@moddx can you approve again?

Review required
At least 1 approving review is required by reviewers with write access. 
1 pending reviewer
@moddx
[moddx](https://github.com/moddx) was requested for review

**Comment by moddx** [comment]
> @moddx can you approve again?
> Review required At least 1 approving review is required by reviewers with **write access**. 

I could, but it doesnt matter, because i dont have right accces

**Comment by didaquis** [comment]
I just wrote an email to Auth0 to ask them to pay attention to this merge request

**Comment by didaquis** [comment]
No one has responded to the email I sent.   ☹️

**Comment by tietthinh** [comment]
Any update on this PR?

**Comment by Hyjaz** [comment]
Any update on this PR?

**Comment by SEKERM** [comment]
@CharlesRea @ArturKlajnerok pls provide an update on this due to criticality.

**Comment by mkrudele** [comment]
When will this PR be merged and a new version of the module published?

**Comment by SEKERM** [comment]
> When will this PR be merged and a new version of the module published?

Please follow up the repo owners PR:
https://github.com/auth0/node-jsonwebtoken/pull/932

**Pull request closed without merging**
