### PR TITLE
fix security with Vulnerable module: base64url

### PR DESCRIPTION
**Pull request by ddtraceweb**
fix security with Vulnerable module: base64url

### CODE REVIEW

**Comment by justingreenberg** [comment]
duplicate of #466

**Comment by justingreenberg** [comment]
>Versions of base64url before 3.0.0 are vulnerable to to out-of-bounds reads (as it allocates uninitialized Buffers when number is passed in input on Node.js 4.x and below

references: 
 - https://hackerone.com/reports/321687
 - https://nodesecurity.io/advisories/658

Node 4/5 are almost EOL and clearly contain vulnerabilities, maybe time to cut a new major and drop support?

**Comment by victor-geere** [comment]
jws 3.1.5 doesn't use base64url. that's the whole point of this merge request. we can't use this package while it has a security advisory. please reconsider.

**Comment by cjcodes** [comment]
@jfromaniello or @ziluvatar can you weigh in here? Haven't heard anything from you guys since this became an issue 5 days ago.

This issue seems to be blocking a lot of folks, especially now that `npm audit` is becoming a bigger part of teams' deployment pipelines.

**Comment by ziluvatar** [comment]
@ddtraceweb can you update your branch with latest commits from master branch? I fixed the CI there.

**Comment by ziluvatar** [comment]
Thanks for the PR @ddtraceweb ! I finally used my PR because I couldn't merge yours without rebasing master. Released on v8.2.2.

**Pull request closed without merging**
