### PR TITLE
Reduce size of NPM package

### PR DESCRIPTION
**Pull request by jorrit**
This change removes the following files/directories:

- .history
- bin
- test
- .jshintrc
- .npmignore
- .travis.yml
- CHANGELOG.md

The lib directory, decode.js, sign.js and verify.js are kept explicitly, README.md, package.json, LICENSE and index.js are kept implicitly.

If you want to keep some of the above files please let me know and I update the PR.

### CODE REVIEW

**Comment by purificant** [comment]
👍

**Comment by ziluvatar** [comment]
Nice! LGTM.
Small comment, CHANGELOG is kept implicitly as well.
I'll mark it as `next-major` (although I hope no one was depending on the removed files by doing dark stuff). There are some PRs in the air waiting for next-major, I want to have this and them soon merged.

**Comment by jorrit** [comment]
I never realized that the changelog was kept as well, thanks for pointing that out!

**Comment by rafaelrpinto** [comment]
If possible, please update the Joi dependency because they had this same issue. 

The version that this module uses (6.10.1) has a package size of 703 kB and the current Joi version (10.6.0) has 166,9 kB.

**Comment by jorrit** [comment]
Thanks for merging!

**Pull request merged**
