### PR TITLE
Update dev-dependencies to satisfy npm audit

### PR DESCRIPTION
**Pull request by JacoKoster**

### CODE REVIEW

**Comment by JacoKoster** [comment]
Time to stop supporting older versions of node... ;-)

**Comment by ziluvatar** [comment]
@JacoKoster sorry I didn't give you any ACK, I saw it and I thought 🤔 "Not sure about forcing a major release dropping node support because of dev dependencies"

**Comment by JacoKoster** [comment]
@ziluvatar How do you want to proceed? Shall i make it mergeable again?

**Comment by ziluvatar** [comment]
I think just leave it as is for now. At the very moment we drop v4 support I/you can resolve the conflicts and merge.

**Comment by panva** [comment]
Closing this as stale. When we decide to drop specific node version support with a major update we'll address dev deps.

**Pull request closed without merging**
